# ==================================================================== #
#            https://t.me/BeeDevelopers- Твоя любимая студия           #
# ==================================================================== #

anchor:
  # Радиус в блоках, в котором игроки получают награду (опыт/монеты) и видят эффекты
  player-radius: 12.0

  # Режим награды:
  # EXPERIENCE - только опыт
  # COINS - только монеты
  # EXPERIENCE_AND_COINS - опыт и монеты одновременно
  reward-mode: EXPERIENCE_AND_COINS

  # Количество опыта за цикл
  experience: 150

  # Команда начисления монет (%player_name% заменяется на ник игрока)
  coins-command: 'eco give %player_name% 150'

  # Время наполнения якоря в секундах (по умолчанию 20 секунд)
  charge-seconds: 20

  # Чередование режимов награды по времени
  cycle:
    enabled: false
    first-mode: EXPERIENCE
    second-mode: COINS
    switch-seconds: 300

  # Настройки выпадения предметов из GUI редактора (/wellsun editor)
  item-drop:
    enabled: true
    min-count: 1
    max-count: 3
    # Диапазон расстояния в блоках, на которое вылетают предметы от якоря (например: от 1.0 до 5.0)
    distance-min-blocks: 1.0
    distance-max-blocks: 10.0
    # Показывать ли цветное название над выпавшим предметом (true - включено, false - выключено)
    show-display-name: false
    # Отображать ли шлейф из частиц под выпавшим предметом (true - включено, false - выключено)
    show-particles: false

  # Время жизни выброшенных предметов в секундах
  item-lifetime-seconds: 60

  # Начальная высота выброса над якорем
  item-launch-height: 0.8

# Примечание: Все настройки частиц и звуков находятся в файле particle.yml
