name: BeeSun
version: 1.0.0
main: ru.amiloxs.beesun.BeeSun
api-version: '1.16'
authors: [Amiloxs]
website: https://t.me/BeeDevelopers
commands:
  beesun:
    description: Управление BeeSun
    usage: /beesun [reload|editor]
    aliases: [beesun]
    permission: beesun.admin
permissions:
  beesun.admin:
    default: op
